export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Features } from "./Features";
export { default as Products } from "./Products";
export { default as About } from "./About";
export { default as Testimonials } from "./Testimonials";
export { default as CTA } from "./CTA";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
